In [2]:
import pandas as pd

In [3]:
files = [
    "RBKO.csv", "TEB.csv", "NLB.csv", "PCB.csv",
    "BE.csv", "CRE.csv", "PRI.csv", "ZBA.csv"
]

dfs = []
for file in files:
    df = pd.read_csv(file)
    
    df = df.drop(columns=["Unnamed: 0"])
    
    dfs.append(df)

final_df = pd.concat(dfs, ignore_index=True)

In [4]:
final_df

,BANK_ID,REPORT_DATE,STATEMENT_TYPE,CATEGORY_TYPE,CATEGORY_CODE,ORIGINAL_CATEGORY,PREVIOUS_VALUE,CURRENT_VALUE,CURR_ID,FILE_NAME,DATA_SOURCE,EXTRACTION_DATE,DT_REPORT
0,8.0,2018-12-31,INCOME_STATEMENT,INCOME,14.0,Fitimi (humbja) para tatimit,19602.0,26707.0,1.0,rbko_is_31.12.2018.pdf,Raiffeisen Kosovo,2026-03-18,2018-12-31
1,8.0,2018-12-31,INCOME_STATEMENT,INCOME,4.0,Të hyrat nga tarifat dhe komisionet,13511.0,17569.0,1.0,rbko_is_31.12.2018.pdf,Raiffeisen Kosovo,2026-03-18,2018-12-31
2,8.0,2018-12-31,INCOME_STATEMENT,INCOME,1.0,Të hyrat nga interesi,30651.0,43090.0,1.0,rbko_is_31.12.2018.pdf,Raiffeisen Kosovo,2026-03-18,2018-12-31
3,8.0,2018-12-31,INCOME_STATEMENT,INCOME,17.0,Të ardhurat tjera gjithëpërfshirëse,-57.0,-345.0,1.0,rbko_is_31.12.2018.pdf,Raiffeisen Kosovo,2026-03-18,2018-12-31
4,8.0,2018-12-31,INCOME_STATEMENT,INCOME,7.0,Neto të hyrat nga tregtimi,-244.0,-178.0,1.0,rbko_is_31.12.2018.pdf,Raiffeisen Kosovo,2026-03-18,2018-12-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9521,9.0,2025-12-31,INCOME_STATEMENT,INCOME,4.0,Të hyrat nga tarifat dhe komisionet,479.0,87.0,1.0,zba_is_31.12.2025.pdf,Ziraat Bank,2026-03-18,2025-12-31
9522,9.0,2025-12-31,INCOME_STATEMENT,INCOME,5.0,Shpenzimet e tarifave dhe komisioneve,353.0,98.0,1.0,zba_is_31.12.2025.pdf,Ziraat Bank,2026-03-18,2025-12-31
9523,9.0,2025-12-31,INCOME_STATEMENT,INCOME,6.0,Neto të hyrat nga tarifat dhe komisionet,126.0,11.0,1.0,zba_is_31.12.2025.pdf,Ziraat Bank,2026-03-18,2025-12-31
9524,9.0,2025-12-31,INCOME_STATEMENT,INCOME,80.0,Neto të hyrat tjera,150.0,18.0,1.0,zba_is_31.12.2025.pdf,Ziraat Bank,2026-03-18,2025-12-31
9525,9.0,2025-12-31,INCOME_STATEMENT,INCOME,9.0,Neto të hyrat (shpenzimet) tjera operative,3396.0,813.0,1.0,zba_is_31.12.2025.pdf,Ziraat Bank,2026-03-18,2025-12-31

In [5]:
final_df = final_df.drop(columns=["CURR_ID"])

In [7]:
bank_mapping = {
    'Raiffeisen Kosovo': 1,
    'TEB Kosovo': 2,
    'NLB Bank': 3,
    'ProCredit Bank': 4,
    'Banka Ekonomike': 5,
    'Credins Bank': 6,
    'PriBank': 7,
    'Ziraat Bank': 8
}

final_df['BANK_ID'] = final_df['DATA_SOURCE'].map(bank_mapping)

In [8]:
final_df

,BANK_ID,REPORT_DATE,STATEMENT_TYPE,CATEGORY_TYPE,CATEGORY_CODE,ORIGINAL_CATEGORY,PREVIOUS_VALUE,CURRENT_VALUE,FILE_NAME,DATA_SOURCE,EXTRACTION_DATE,DT_REPORT
0,1,2018-12-31,INCOME_STATEMENT,INCOME,14.0,Fitimi (humbja) para tatimit,19602.0,26707.0,rbko_is_31.12.2018.pdf,Raiffeisen Kosovo,2026-03-18,2018-12-31
1,1,2018-12-31,INCOME_STATEMENT,INCOME,4.0,Të hyrat nga tarifat dhe komisionet,13511.0,17569.0,rbko_is_31.12.2018.pdf,Raiffeisen Kosovo,2026-03-18,2018-12-31
2,1,2018-12-31,INCOME_STATEMENT,INCOME,1.0,Të hyrat nga interesi,30651.0,43090.0,rbko_is_31.12.2018.pdf,Raiffeisen Kosovo,2026-03-18,2018-12-31
3,1,2018-12-31,INCOME_STATEMENT,INCOME,17.0,Të ardhurat tjera gjithëpërfshirëse,-57.0,-345.0,rbko_is_31.12.2018.pdf,Raiffeisen Kosovo,2026-03-18,2018-12-31
4,1,2018-12-31,INCOME_STATEMENT,INCOME,7.0,Neto të hyrat nga tregtimi,-244.0,-178.0,rbko_is_31.12.2018.pdf,Raiffeisen Kosovo,2026-03-18,2018-12-31
...,...,...,...,...,...,...,...,...,...,...,...,...
9521,8,2025-12-31,INCOME_STATEMENT,INCOME,4.0,Të hyrat nga tarifat dhe komisionet,479.0,87.0,zba_is_31.12.2025.pdf,Ziraat Bank,2026-03-18,2025-12-31
9522,8,2025-12-31,INCOME_STATEMENT,INCOME,5.0,Shpenzimet e tarifave dhe komisioneve,353.0,98.0,zba_is_31.12.2025.pdf,Ziraat Bank,2026-03-18,2025-12-31
9523,8,2025-12-31,INCOME_STATEMENT,INCOME,6.0,Neto të hyrat nga tarifat dhe komisionet,126.0,11.0,zba_is_31.12.2025.pdf,Ziraat Bank,2026-03-18,2025-12-31
9524,8,2025-12-31,INCOME_STATEMENT,INCOME,80.0,Neto të hyrat tjera,150.0,18.0,zba_is_31.12.2025.pdf,Ziraat Bank,2026-03-18,2025-12-31
9525,8,2025-12-31,INCOME_STATEMENT,INCOME,9.0,Neto të hyrat (shpenzimet) tjera operative,3396.0,813.0,zba_is_31.12.2025.pdf,Ziraat Bank,2026-03-18,2025-12-31

In [10]:
final_df["CATEGORY_TYPE_NUM"] = final_df["CATEGORY_TYPE"].map({
    "BALANCE": 0,
    "INCOME": 1
})

final_df

,BANK_ID,REPORT_DATE,STATEMENT_TYPE,CATEGORY_TYPE,CATEGORY_CODE,ORIGINAL_CATEGORY,PREVIOUS_VALUE,CURRENT_VALUE,FILE_NAME,DATA_SOURCE,EXTRACTION_DATE,DT_REPORT,CATEGORY_TYPE_NUM
0,1,2018-12-31,INCOME_STATEMENT,INCOME,14.0,Fitimi (humbja) para tatimit,19602.0,26707.0,rbko_is_31.12.2018.pdf,Raiffeisen Kosovo,2026-03-18,2018-12-31,1
1,1,2018-12-31,INCOME_STATEMENT,INCOME,4.0,Të hyrat nga tarifat dhe komisionet,13511.0,17569.0,rbko_is_31.12.2018.pdf,Raiffeisen Kosovo,2026-03-18,2018-12-31,1
2,1,2018-12-31,INCOME_STATEMENT,INCOME,1.0,Të hyrat nga interesi,30651.0,43090.0,rbko_is_31.12.2018.pdf,Raiffeisen Kosovo,2026-03-18,2018-12-31,1
3,1,2018-12-31,INCOME_STATEMENT,INCOME,17.0,Të ardhurat tjera gjithëpërfshirëse,-57.0,-345.0,rbko_is_31.12.2018.pdf,Raiffeisen Kosovo,2026-03-18,2018-12-31,1
4,1,2018-12-31,INCOME_STATEMENT,INCOME,7.0,Neto të hyrat nga tregtimi,-244.0,-178.0,rbko_is_31.12.2018.pdf,Raiffeisen Kosovo,2026-03-18,2018-12-31,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9521,8,2025-12-31,INCOME_STATEMENT,INCOME,4.0,Të hyrat nga tarifat dhe komisionet,479.0,87.0,zba_is_31.12.2025.pdf,Ziraat Bank,2026-03-18,2025-12-31,1
9522,8,2025-12-31,INCOME_STATEMENT,INCOME,5.0,Shpenzimet e tarifave dhe komisioneve,353.0,98.0,zba_is_31.12.2025.pdf,Ziraat Bank,2026-03-18,2025-12-31,1
9523,8,2025-12-31,INCOME_STATEMENT,INCOME,6.0,Neto të hyrat nga tarifat dhe komisionet,126.0,11.0,zba_is_31.12.2025.pdf,Ziraat Bank,2026-03-18,2025-12-31,1
9524,8,2025-12-31,INCOME_STATEMENT,INCOME,80.0,Neto të hyrat tjera,150.0,18.0,zba_is_31.12.2025.pdf,Ziraat Bank,2026-03-18,2025-12-31,1
9525,8,2025-12-31,INCOME_STATEMENT,INCOME,9.0,Neto të hyrat (shpenzimet) tjera operative,3396.0,813.0,zba_is_31.12.2025.pdf,Ziraat Bank,2026-03-18,2025-12-31,1

In [13]:
final_df["DT_REPORT"] = pd.to_datetime(final_df["DT_REPORT"], dayfirst=True, errors="coerce")
final_df["YEAR"] = final_df["DT_REPORT"].dt.year
final_df["QUARTER"] = final_df["DT_REPORT"].dt.quarter

/var/folders/gg/tbq9nzjd05x7705vgx9mgwch0000gn/T/ipykernel_8282/2547425824.py:1: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  final_df["DT_REPORT"] = pd.to_datetime(final_df["DT_REPORT"], dayfirst=True, errors="coerce")

In [14]:
final_df

,BANK_ID,REPORT_DATE,STATEMENT_TYPE,CATEGORY_TYPE,CATEGORY_CODE,ORIGINAL_CATEGORY,PREVIOUS_VALUE,CURRENT_VALUE,FILE_NAME,DATA_SOURCE,EXTRACTION_DATE,DT_REPORT,CATEGORY_TYPE_NUM,YEAR,QUARTER
0,1,2018-12-31,INCOME_STATEMENT,INCOME,14.0,Fitimi (humbja) para tatimit,19602.0,26707.0,rbko_is_31.12.2018.pdf,Raiffeisen Kosovo,2026-03-18,2018-12-31,1,2018.0,4.0
1,1,2018-12-31,INCOME_STATEMENT,INCOME,4.0,Të hyrat nga tarifat dhe komisionet,13511.0,17569.0,rbko_is_31.12.2018.pdf,Raiffeisen Kosovo,2026-03-18,2018-12-31,1,2018.0,4.0
2,1,2018-12-31,INCOME_STATEMENT,INCOME,1.0,Të hyrat nga interesi,30651.0,43090.0,rbko_is_31.12.2018.pdf,Raiffeisen Kosovo,2026-03-18,2018-12-31,1,2018.0,4.0
3,1,2018-12-31,INCOME_STATEMENT,INCOME,17.0,Të ardhurat tjera gjithëpërfshirëse,-57.0,-345.0,rbko_is_31.12.2018.pdf,Raiffeisen Kosovo,2026-03-18,2018-12-31,1,2018.0,4.0
4,1,2018-12-31,INCOME_STATEMENT,INCOME,7.0,Neto të hyrat nga tregtimi,-244.0,-178.0,rbko_is_31.12.2018.pdf,Raiffeisen Kosovo,2026-03-18,2018-12-31,1,2018.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9521,8,2025-12-31,INCOME_STATEMENT,INCOME,4.0,Të hyrat nga tarifat dhe komisionet,479.0,87.0,zba_is_31.12.2025.pdf,Ziraat Bank,2026-03-18,2025-12-31,1,2025.0,4.0
9522,8,2025-12-31,INCOME_STATEMENT,INCOME,5.0,Shpenzimet e tarifave dhe komisioneve,353.0,98.0,zba_is_31.12.2025.pdf,Ziraat Bank,2026-03-18,2025-12-31,1,2025.0,4.0
9523,8,2025-12-31,INCOME_STATEMENT,INCOME,6.0,Neto të hyrat nga tarifat dhe komisionet,126.0,11.0,zba_is_31.12.2025.pdf,Ziraat Bank,2026-03-18,2025-12-31,1,2025.0,4.0
9524,8,2025-12-31,INCOME_STATEMENT,INCOME,80.0,Neto të hyrat tjera,150.0,18.0,zba_is_31.12.2025.pdf,Ziraat Bank,2026-03-18,2025-12-31,1,2025.0,4.0
9525,8,2025-12-31,INCOME_STATEMENT,INCOME,9.0,Neto të hyrat (shpenzimet) tjera operative,3396.0,813.0,zba_is_31.12.2025.pdf,Ziraat Bank,2026-03-18,2025-12-31,1,2025.0,4.0

In [15]:
final_df["YEAR"] = final_df["YEAR"].astype("Int64")
final_df["QUARTER"] = final_df["QUARTER"].astype("Int64")
final_df["CATEGORY_CODE"] = final_df["CATEGORY_CODE"].astype("Int64")

In [16]:
final_df

,BANK_ID,REPORT_DATE,STATEMENT_TYPE,CATEGORY_TYPE,CATEGORY_CODE,ORIGINAL_CATEGORY,PREVIOUS_VALUE,CURRENT_VALUE,FILE_NAME,DATA_SOURCE,EXTRACTION_DATE,DT_REPORT,CATEGORY_TYPE_NUM,YEAR,QUARTER
0,1,2018-12-31,INCOME_STATEMENT,INCOME,14,Fitimi (humbja) para tatimit,19602.0,26707.0,rbko_is_31.12.2018.pdf,Raiffeisen Kosovo,2026-03-18,2018-12-31,1,2018,4
1,1,2018-12-31,INCOME_STATEMENT,INCOME,4,Të hyrat nga tarifat dhe komisionet,13511.0,17569.0,rbko_is_31.12.2018.pdf,Raiffeisen Kosovo,2026-03-18,2018-12-31,1,2018,4
2,1,2018-12-31,INCOME_STATEMENT,INCOME,1,Të hyrat nga interesi,30651.0,43090.0,rbko_is_31.12.2018.pdf,Raiffeisen Kosovo,2026-03-18,2018-12-31,1,2018,4
3,1,2018-12-31,INCOME_STATEMENT,INCOME,17,Të ardhurat tjera gjithëpërfshirëse,-57.0,-345.0,rbko_is_31.12.2018.pdf,Raiffeisen Kosovo,2026-03-18,2018-12-31,1,2018,4
4,1,2018-12-31,INCOME_STATEMENT,INCOME,7,Neto të hyrat nga tregtimi,-244.0,-178.0,rbko_is_31.12.2018.pdf,Raiffeisen Kosovo,2026-03-18,2018-12-31,1,2018,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9521,8,2025-12-31,INCOME_STATEMENT,INCOME,4,Të hyrat nga tarifat dhe komisionet,479.0,87.0,zba_is_31.12.2025.pdf,Ziraat Bank,2026-03-18,2025-12-31,1,2025,4
9522,8,2025-12-31,INCOME_STATEMENT,INCOME,5,Shpenzimet e tarifave dhe komisioneve,353.0,98.0,zba_is_31.12.2025.pdf,Ziraat Bank,2026-03-18,2025-12-31,1,2025,4
9523,8,2025-12-31,INCOME_STATEMENT,INCOME,6,Neto të hyrat nga tarifat dhe komisionet,126.0,11.0,zba_is_31.12.2025.pdf,Ziraat Bank,2026-03-18,2025-12-31,1,2025,4
9524,8,2025-12-31,INCOME_STATEMENT,INCOME,80,Neto të hyrat tjera,150.0,18.0,zba_is_31.12.2025.pdf,Ziraat Bank,2026-03-18,2025-12-31,1,2025,4
9525,8,2025-12-31,INCOME_STATEMENT,INCOME,9,Neto të hyrat (shpenzimet) tjera operative,3396.0,813.0,zba_is_31.12.2025.pdf,Ziraat Bank,2026-03-18,2025-12-31,1,2025,4

In [20]:
final_order = ['DATA_SOURCE', 'FILE_NAME', 'BANK_ID', 'DT_REPORT', 
                 'EXTRACTION_DATE', 'STATEMENT_TYPE', 'CATEGORY_TYPE', 
                 'ORIGINAL_CATEGORY', 'CATEGORY_CODE', 'CURRENT_VALUE', 
                 'PREVIOUS_VALUE', 'CATEGORY_TYPE_NUM', 'REPORT_DATE', 
                 'YEAR', 'QUARTER']

final_df = final_df.reindex(columns=desired_order)
final_df

,DATA_SOURCE,FILE_NAME,BANK_ID,DT_REPORT,EXTRACTION_DATE,STATEMENT_TYPE,CATEGORY_TYPE,ORIGINAL_CATEGORY,CATEGORY_CODE,CURRENT_VALUE,PREVIOUS_VALUE,CATEGORY_TYPE_NUM,REPORT_DATE,YEAR,QUARTER
0,Raiffeisen Kosovo,rbko_is_31.12.2018.pdf,1,2018-12-31,2026-03-18,INCOME_STATEMENT,INCOME,Fitimi (humbja) para tatimit,14,26707.0,19602.0,1,2018-12-31,2018,4
1,Raiffeisen Kosovo,rbko_is_31.12.2018.pdf,1,2018-12-31,2026-03-18,INCOME_STATEMENT,INCOME,Të hyrat nga tarifat dhe komisionet,4,17569.0,13511.0,1,2018-12-31,2018,4
2,Raiffeisen Kosovo,rbko_is_31.12.2018.pdf,1,2018-12-31,2026-03-18,INCOME_STATEMENT,INCOME,Të hyrat nga interesi,1,43090.0,30651.0,1,2018-12-31,2018,4
3,Raiffeisen Kosovo,rbko_is_31.12.2018.pdf,1,2018-12-31,2026-03-18,INCOME_STATEMENT,INCOME,Të ardhurat tjera gjithëpërfshirëse,17,-345.0,-57.0,1,2018-12-31,2018,4
4,Raiffeisen Kosovo,rbko_is_31.12.2018.pdf,1,2018-12-31,2026-03-18,INCOME_STATEMENT,INCOME,Neto të hyrat nga tregtimi,7,-178.0,-244.0,1,2018-12-31,2018,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9521,Ziraat Bank,zba_is_31.12.2025.pdf,8,2025-12-31,2026-03-18,INCOME_STATEMENT,INCOME,Të hyrat nga tarifat dhe komisionet,4,87.0,479.0,1,2025-12-31,2025,4
9522,Ziraat Bank,zba_is_31.12.2025.pdf,8,2025-12-31,2026-03-18,INCOME_STATEMENT,INCOME,Shpenzimet e tarifave dhe komisioneve,5,98.0,353.0,1,2025-12-31,2025,4
9523,Ziraat Bank,zba_is_31.12.2025.pdf,8,2025-12-31,2026-03-18,INCOME_STATEMENT,INCOME,Neto të hyrat nga tarifat dhe komisionet,6,11.0,126.0,1,2025-12-31,2025,4
9524,Ziraat Bank,zba_is_31.12.2025.pdf,8,2025-12-31,2026-03-18,INCOME_STATEMENT,INCOME,Neto të hyrat tjera,80,18.0,150.0,1,2025-12-31,2025,4
9525,Ziraat Bank,zba_is_31.12.2025.pdf,8,2025-12-31,2026-03-18,INCOME_STATEMENT,INCOME,Neto të hyrat (shpenzimet) tjera operative,9,813.0,3396.0,1,2025-12-31,2025,4

In [22]:
final_df['EXTRACTION_DATE'] = pd.to_datetime(final_df['EXTRACTION_DATE'])
final_df['REPORT_DATE'] = pd.to_datetime(final_df['REPORT_DATE'])

In [24]:
final_df

,DATA_SOURCE,FILE_NAME,BANK_ID,DT_REPORT,EXTRACTION_DATE,STATEMENT_TYPE,CATEGORY_TYPE,ORIGINAL_CATEGORY,CATEGORY_CODE,CURRENT_VALUE,PREVIOUS_VALUE,CATEGORY_TYPE_NUM,REPORT_DATE,YEAR,QUARTER
0,Raiffeisen Kosovo,rbko_is_31.12.2018.pdf,1,2018-12-31,2026-03-18,INCOME_STATEMENT,INCOME,Fitimi (humbja) para tatimit,14,26707.0,19602.0,1,2018-12-31,2018,4
1,Raiffeisen Kosovo,rbko_is_31.12.2018.pdf,1,2018-12-31,2026-03-18,INCOME_STATEMENT,INCOME,Të hyrat nga tarifat dhe komisionet,4,17569.0,13511.0,1,2018-12-31,2018,4
2,Raiffeisen Kosovo,rbko_is_31.12.2018.pdf,1,2018-12-31,2026-03-18,INCOME_STATEMENT,INCOME,Të hyrat nga interesi,1,43090.0,30651.0,1,2018-12-31,2018,4
3,Raiffeisen Kosovo,rbko_is_31.12.2018.pdf,1,2018-12-31,2026-03-18,INCOME_STATEMENT,INCOME,Të ardhurat tjera gjithëpërfshirëse,17,-345.0,-57.0,1,2018-12-31,2018,4
4,Raiffeisen Kosovo,rbko_is_31.12.2018.pdf,1,2018-12-31,2026-03-18,INCOME_STATEMENT,INCOME,Neto të hyrat nga tregtimi,7,-178.0,-244.0,1,2018-12-31,2018,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9521,Ziraat Bank,zba_is_31.12.2025.pdf,8,2025-12-31,2026-03-18,INCOME_STATEMENT,INCOME,Të hyrat nga tarifat dhe komisionet,4,87.0,479.0,1,2025-12-31,2025,4
9522,Ziraat Bank,zba_is_31.12.2025.pdf,8,2025-12-31,2026-03-18,INCOME_STATEMENT,INCOME,Shpenzimet e tarifave dhe komisioneve,5,98.0,353.0,1,2025-12-31,2025,4
9523,Ziraat Bank,zba_is_31.12.2025.pdf,8,2025-12-31,2026-03-18,INCOME_STATEMENT,INCOME,Neto të hyrat nga tarifat dhe komisionet,6,11.0,126.0,1,2025-12-31,2025,4
9524,Ziraat Bank,zba_is_31.12.2025.pdf,8,2025-12-31,2026-03-18,INCOME_STATEMENT,INCOME,Neto të hyrat tjera,80,18.0,150.0,1,2025-12-31,2025,4
9525,Ziraat Bank,zba_is_31.12.2025.pdf,8,2025-12-31,2026-03-18,INCOME_STATEMENT,INCOME,Neto të hyrat (shpenzimet) tjera operative,9,813.0,3396.0,1,2025-12-31,2025,4